### PR TITLE
Fix bugs in opening push and geometry pull

### LINKED ISSUE #58: Opening geometry not correctly placed
During testing for the 3.3 beta, it was discovered that opening geometry for rooms which are not on the ground floor were not correctly showing in the DIALux model, rather they were 'floating' higher above the wall geometry.

The ground floor spaces were fine, this was only affecting rooms on levels greater than the ground level.

Owing to current DIALux take up in the beta, this will not be fixed before the beta unless someone else is able to, thus will be fixed in early 4.0 alphas.

### LINKED ISSUE #59: Pull not functioning
Following testing of the 3.3 alphas, it was found that the test model could not pull without producing errors. This should be investigated and resolved in early 4.0.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #58 
Fixes #59 

 ### Test files
See Test Procedure for this toolkit

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by JohannaOlin1 — APPROVED** [review]
LGTM

**Pull request merged**
