### PR TITLE
Fix pulling opening geometry

### LINKED ISSUE #65: Rotated doors in pulled model
#### Description:
When pulling a model from DIALux into Rhino the doors are flipped perpendicular to the walls.

image

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #65 

 ### Test files

 ### Changelog

 ### Additional comments
Also moves all oM and Engine stuff to the Adapter to avoid revealing this to the UI and needing to version it.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check all

**Review by JohannaOlin1 — APPROVED** [review]
Works when tested!

**Pull request merged**
